### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by andrew-m-p** [mr-phlames/leaf-php-boilerplate#264]
Hello,
I'm trying :
app()->setNamespace('\App\Controllers');
app()->get('/myroute/{action}', 'MyrouteController@update');

Is the route valid ? Even though MyrouteController exists it does not run the public function update() in the class.

**Comment by andrew-m-p** [comment]
I found the bug , this does not seem to work:
app()->csrf([
    'except' => ['/myroute/{action}' ],
  ]);
 I had to put the 'except' key directly in csrf.php , then the route works

**Comment by mychidarko** [comment]
Hi @andrew-m-p can you pls give a bit more info. What happens when you don't exclude your route from the CSRF except and are you using Leaf MVC?

**Comment by andrew-m-p** [comment]
Yes I am using MVC , but I have also API REST calls to handle (mixed). 
If I don't exclude then the API REST route does not work.

**Comment by ibnsultan** [comment]
@andrew-m-p It looks like the issue you're encountering is related to how you've defined the route in the `except` array. This isn't a bug but rather a misconfiguration of the route pattern.

### Usage Notes for CSRF Exemptions
When defining routes to exempt from CSRF protection, you can use explicit routes or expressions to match multiple routes. Here are some key points to keep in mind:

- **Explicit Routes**: If you specify `'user/login'`, CSRF checks will be skipped for that exact route.
- **Expressions**: These are flexible patterns for dynamic segments within routes, allowing you to bypass CSRF checks on multiple routes that follow a similar pattern.
- **Security Consideration**: Be cautious when exempting routes from CSRF protection. Only exempt routes where it's absolutely necessary to avoid security vulnerabilities.

### Explanation of Expressions

| Expression | Description                                           | Example                    |
|------------|-------------------------------------------------------|----------------------------|
| `{int}`    | Matches integer values only                           | `order/{int}` → `order/10` |
| `{slug}`   | Matches alphanumeric characters (letters & numbers)   | `user/{slug}` → `user/janedoe98` |
| `{any}`    | Matches any character except slashes (`/`)            | `view/{any}` → `view/hello-world-153` |
| `{wild}`   | Matches any character including slashes (`/`)         | `path/{wild}` → `path/any/file/path` |

### Solution
When using route expressions like `{action}`, Leaf expects the expression to match specific patterns such as `{int}`, `{slug}`, `{any}`, or `{wild}`. Your current definition:

```php
app()->csrf([
    'except' => ['/myroute/{action}'],
]);
```

won't work as intended because `{action}` is not a recognized expression in Leaf's CSRF configuration.

### Correct Approach
To fix this, you can use one of the predefined expressions like `{any}` or `{slug}` depending on your use case. Here's how:

```php
app()->csrf([
    'except' => ['/myroute/{any}'],
]);
```


### Recommended Configuration
If you prefer defining CSRF exemptions globally, adding them directly in `configs/csrf.php` is also a valid approach. However, the dynamic expression needs to be correct in both configurations.

Let me know if this resolves your issue!

cc: @mychidarko

**Comment by andrew-m-p** [comment]
Hello, I added in the global configuration and then tested for csrf token in my routine.
Your explaination was excellent, it should be added to the doc to help others understand better.
Thanks

**Comment by andrew-m-p** [comment]
We can close the issue as well.
